# Generated by Django 4.1.3 on 2022-11-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_options_alter_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_date',)},
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
