# Generated by Django 4.1.3 on 2022-11-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='sub_category',
        ),
    ]
